title: "Maciej Kozubal"
description: "Full-stack Data Scientist & MLOps Engineer building production-grade ML and LLM systems."
minimal_mistakes_skin: contrast   # crisp dark-on-light palette
# --- keep the rest of your current config above this line ---

author:
  name   : "Maciej Kozubal"
  avatar : "/assets/images/avatar.jpg"
  bio    : >-
    Data Scientist & ML Engineer with end-to-end expertise in ML, MLOps, GenAI, LLMs, and semiconductor physics.
    Currently at Seldon building and deploying production-grade ML/LLM architectures with a focus on performance,
    scalability, and observability.
  location: "London, UK"
  links:
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin"
      url  : "https://linkedin.com/in/maciejkozubal"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/maciejkozubal"
    - label: "Google Scholar"
      icon : "fas fa-fw fa-graduation-cap"
      url  : "https://scholar.google.com/citations?user=emWmhaIAAAAJ"
    - label: "Email"
      icon : "fas fa-fw fa-envelope"
      url  : "mailto:mkoz001@gmail.com"

# Show sidebar (author profile) site-wide
author_profile: true

sass:
  style: compressed
