# --- Basic Site Settings ---

title: "Maciej Kozubal"
# Purpose: Sets the main title for your website.
# Usage: Displayed in browser tabs, headers, and potentially by search engines.

description: "Full-stack Data Scientist & MLOps Engineer"
# Purpose: A brief description of your site's content or purpose.
# Usage: Often used in HTML meta tags for search engine results (SEO).

baseurl: ""
# Purpose: Specifies a subpath if your site lives in a subdirectory of a domain.
# Usage: For a site like https://username.github.io/my-repo/, baseurl would be "/my-repo".
# For a root user/org site like yours (https://maciejkozubal.github.io), it should be empty "".

url: "https://maciejkozubal.github.io"
# Purpose: The absolute base URL for your site, including the protocol (https://).
# Usage: Used by Jekyll and themes/plugins to generate correct absolute links for assets, feeds, SEO tags, etc.

# --- Theme Selection ---
# Purpose: Selects the visual theme for your Jekyll site.
# You should use EITHER 'theme:' OR 'remote_theme:', not both.

# theme: jekyll-theme-minimal
# Purpose: (Commented out) Selects an officially supported, gem-based theme.
# Usage: Uncomment this and remove 'remote_theme' to use a gem-based theme like 'minimal'.

remote_theme: cotes2020/jekyll-theme-chirpy
# Purpose: Selects a theme hosted in a separate GitHub repository.
# Usage: Specifies the theme using the 'owner/repository-name' format. Currently set to use the 'Chirpy' theme.
# Requires the 'jekyll-remote-theme' plugin (see below).

# --- Build Settings & Plugins ---

markdown: kramdown
# Purpose: Specifies the processor Jekyll should use to convert Markdown (.md) files into HTML.
# Usage: 'kramdown' is the default for GitHub Pages and supports GitHub Flavored Markdown (GFM).

plugins:
  - jekyll-remote-theme
  # Purpose: Enables the use of the 'remote_theme' setting above. This plugin fetches the theme from GitHub during the build.
  # Usage: Required when using 'remote_theme:'.

  # - jekyll-feed
  # Purpose: (Commented out) Automatically generates an Atom (RSS-like) feed for your posts.
  # Usage: Useful if you have a blog section and want users to subscribe to updates. Requires configuration.

  # - jekyll-seo-tag
  # Purpose: (Commented out) Automatically adds metadata tags for search engines (SEO) like title tags, description, canonical URLs, etc.
  # Usage: Generally recommended for better search engine visibility.