title: "Maciej Kozubal v2"
description: "Full-stack Data Scientist & MLOps Engineer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maciejkozubal.github.io" # the base hostname & protocol for your site

# ----- Theme Selection -----
# Remove or comment out the 'remote_theme' line if it exists
# remote_theme: "mmistakes/minimal-mistakes"
theme: jekyll-theme-cayman # Choose one of the supported themes