title: "Maciej Kozubal"
email: "maciej@example.com"
description: >-
  Machine Learning & MLOps Engineer — building and deploying models at scale.
twitter_username: maciejkozubal
github_username: maciejkozubal
minimal_mistakes_skin: air
search: true

author:
  name   : "Maciej Kozubal"
  avatar : "/assets/images/avatar.jpg"
  bio: "Full-stack developer and ML/MLOps engineer with a passion for building scalable AI systems and data-driven applications."
  location: "London, UK"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/maciejkozubal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maciejkozubal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/maciejkozubal"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:maciej@example.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/maciejkozubal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maciejkozubal"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/maciejkozubal"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
